//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoboChat.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RoboChat.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TableRow xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;&gt;&lt;TableCell ColumnSpan=&quot;4&quot;&gt;&lt;Table CellSpacing=&quot;0&quot; Margin=&quot;0,10,0,10&quot;&gt;&lt;Table.Columns&gt;&lt;TableColumn /&gt;&lt;TableColumn Width=&quot;100&quot; /&gt;&lt;TableColumn /&gt;&lt;/Table.Columns&gt;&lt;TableRowGroup&gt;&lt;TableRow&gt;&lt;TableCell&gt;&lt;Paragraph Padding=&quot;0,5,0,0&quot;&gt;&lt;Line X2=&quot;1&quot; Stretch=&quot;Fill&quot; Stroke=&quot;#FFC8C8C8&quot; StrokeThickness=&quot;2&quot; /&gt;&lt;/Paragraph&gt;&lt;/TableCell&gt;&lt;TableCell TextAlignment=&quot;Center&quot;&gt;&lt;Paragraph Foreground=&quot;#FF808080&quot;&gt;[TIME]&lt;/Paragraph&gt;&lt;/TableCell&gt;&lt;TableCell&gt;&lt;Paragraph Pa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TableRow xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:rc=&quot;clr-namespace:RoboChat;assembly=RoboChat&quot;&gt;&lt;TableCell&gt;&lt;Paragraph Padding=&quot;0,4,0,0&quot;&gt;&lt;Span ToolTip=&quot;[TOOLTIP]&quot;&gt;&lt;Span FontSize=&quot;9&quot; Foreground=&quot;#FFC8C8C8&quot;&gt;[DATE]&lt;/Span&gt;&lt;LineBreak/&gt;&lt;Span Foreground=&quot;#FF808080&quot;&gt;[TIME]&lt;/Span&gt;&lt;/Span&gt;&lt;/Paragraph&gt;&lt;/TableCell&gt;&lt;TableCell Padding=&quot;0,10,0,0&quot;&gt;&lt;BlockUIContainer&gt;&lt;Image Source=&quot;pack://application:,,,/Resources;component/images/lock_small.png&quot; Visibility=&quot;[LOCK]&quot; Width=&quot;16&quot;/&gt;&lt;/BlockUIContaine [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReceivedMessage {
            get {
                return ResourceManager.GetString("ReceivedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TableRow xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:rc=&quot;clr-namespace:RoboChat;assembly=RoboChat&quot;&gt;&lt;TableCell&gt;&lt;Paragraph Padding=&quot;0,10,0,0&quot;&gt;&lt;Span Foreground=&quot;#FF808080&quot; ToolTip=&quot;[TOOLTIP]&quot;&gt;[TIME]&lt;/Span&gt;&lt;/Paragraph&gt;&lt;/TableCell&gt;&lt;TableCell Padding=&quot;0,10,0,0&quot;&gt;&lt;BlockUIContainer&gt;&lt;Image Source=&quot;pack://application:,,,/Resources;component/images/lock_small.png&quot; Visibility=&quot;[LOCK]&quot; Width=&quot;16&quot;/&gt;&lt;/BlockUIContainer&gt;&lt;/TableCell&gt;&lt;TableCell Padding=&quot;0,3,0,0&quot;&gt;&lt;BlockUIContainer&gt;&lt;Image Source=&quot;pac [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReceivedMessageToday {
            get {
                return ResourceManager.GetString("ReceivedMessageToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon RoboChat32 {
            get {
                object obj = ResourceManager.GetObject("RoboChat32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TableRow xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:gif=&quot;https://github.com/XamlAnimatedGif/XamlAnimatedGif&quot; xmlns:rc=&quot;clr-namespace:RoboChat;assembly=RoboChat&quot;&gt;&lt;TableCell&gt;&lt;Paragraph Padding=&quot;0,4,0,0&quot;&gt;&lt;Span ToolTip=&quot;[TOOLTIP]&quot;&gt;&lt;Span FontSize=&quot;9&quot; Foreground=&quot;#FFC8C8C8&quot;&gt;[DATE]&lt;/Span&gt;&lt;LineBreak/&gt;&lt;Span Foreground=&quot;#FF808080&quot;&gt;[TIME]&lt;/Span&gt;&lt;/Span&gt;&lt;/Paragraph&gt;&lt;/TableCell&gt;&lt;TableCell Padding=&quot;0,10,0,0&quot;&gt;&lt;BlockUIContainer&gt;&lt;Image Source=&quot;pack://application:,,,/Resources;component/images/lo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SendingMessage {
            get {
                return ResourceManager.GetString("SendingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TableRow xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:gif=&quot;https://github.com/XamlAnimatedGif/XamlAnimatedGif&quot; xmlns:rc=&quot;clr-namespace:RoboChat;assembly=RoboChat&quot;&gt;&lt;TableCell&gt;&lt;Paragraph Padding=&quot;0,10,0,0&quot;&gt;&lt;Span Foreground=&quot;#FF808080&quot; ToolTip=&quot;[TOOLTIP]&quot;&gt;[TIME]&lt;/Span&gt;&lt;/Paragraph&gt;&lt;/TableCell&gt;&lt;TableCell Padding=&quot;0,10,0,0&quot;&gt;&lt;BlockUIContainer&gt;&lt;Image Source=&quot;pack://application:,,,/Resources;component/images/lock_small.png&quot; Visibility=&quot;[LOCK]&quot; Width=&quot;16&quot;/&gt;&lt;/BlockUIContainer&gt;&lt;/TableCell&gt;&lt;T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SendingMessageToday {
            get {
                return ResourceManager.GetString("SendingMessageToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TableRow xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:rc=&quot;clr-namespace:RoboChat;assembly=RoboChat&quot;&gt;&lt;TableCell&gt;&lt;Paragraph Padding=&quot;0,4,0,0&quot;&gt;&lt;Span ToolTip=&quot;[TOOLTIP]&quot;&gt;&lt;Span FontSize=&quot;9&quot; Foreground=&quot;#FFC8C8C8&quot;&gt;[DATE]&lt;/Span&gt;&lt;LineBreak/&gt;&lt;Span Foreground=&quot;#FF808080&quot;&gt;[TIME]&lt;/Span&gt;&lt;/Span&gt;&lt;/Paragraph&gt;&lt;/TableCell&gt;&lt;TableCell Padding=&quot;0,10,0,0&quot;&gt;&lt;BlockUIContainer&gt;&lt;Image Source=&quot;pack://application:,,,/Resources;component/images/lock_small.png&quot; Visibility=&quot;[LOCK]&quot; Width=&quot;16&quot;/&gt;&lt;/BlockUIContaine [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SentMessage {
            get {
                return ResourceManager.GetString("SentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TableRow xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:rc=&quot;clr-namespace:RoboChat;assembly=RoboChat&quot;&gt;&lt;TableCell&gt;&lt;Paragraph Padding=&quot;0,10,0,0&quot;&gt;&lt;Span Foreground=&quot;#FF808080&quot; ToolTip=&quot;[TOOLTIP]&quot;&gt;[TIME]&lt;/Span&gt;&lt;/Paragraph&gt;&lt;/TableCell&gt;&lt;TableCell Padding=&quot;0,10,0,0&quot;&gt;&lt;BlockUIContainer&gt;&lt;Image Source=&quot;pack://application:,,,/Resources;component/images/lock_small.png&quot; Visibility=&quot;[LOCK]&quot; Width=&quot;16&quot;/&gt;&lt;/BlockUIContainer&gt;&lt;/TableCell&gt;&lt;TableCell /&gt;&lt;TableCell&gt;&lt;BlockUIContainer&gt;&lt;Border CornerRadius=&quot;1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SentMessageToday {
            get {
                return ResourceManager.GetString("SentMessageToday", resourceCulture);
            }
        }
    }
}
